### ISSUE TITLE
Program crashed abruptly after training max steps

### ISSUE THREAD

**Issue by JizeCao** [mc-lan/SmooSeg#2]
The training snippet would terminate after training max_steps (defined in train_config.yaml) abruptly, and the newest checkpoint would not be saved/validated. Thus, there would be only temporary checkpoints saved for every four epoch. Do we have to manually rename the checkpoint for evaluation? (I suppose that the training script should handle it and generate the final checkpoint directly for evaluation.)

**Comment by mc-lan** [comment]
It should work well if you use the torch version that I provide in the README.

**Comment by JizeCao** [comment]
Hmm... That's kind of wired. I have run the train_segmentation.py 8 times and only one of them exit the program properly. And none of them evaluate on the last checkpoint. (The only saved checkpoint is the one at step=2000 for the cityscapes dataset). The performance on that checkpoint is slightly lower than the reported performance. Gonna check it more carefully.

**Comment by mc-lan** [comment]
Thanks for your interest.
I actually tested it according to the REAME, and it works well on my machine. You could run eval_segmentation.py using the saved checkpoint.

**Comment by JizeCao** [comment]
What type of GPU is using for the training? It seems that for some reasons, the mixed precision processed by Tensor core would greatly influence the result. With the same hyper-parameter setting, an RTX 4000 (without tensor core) can achieve 83% acc on CityScapes dataset (better than the result in paper) but only 77% acc with an A100.

**Comment by mc-lan** [comment]
We used an RTX 3090 for training.
